<?php

/**
 * @file
 * Contains icon_bundle_api.module.
 */

declare(strict_types=1);

/**
 * Implements the hook_preprocess_HOOK() for details.
 *
 * @phpstan-param array{element?: array{'#type'?:mixed}, value?: mixed} $variables
 */
function icon_bundle_api_preprocess_details(array &$variables): void {
  $element = $variables['element'] ?? [];
  if ('icon_picker' === ($element['#type'] ?? null) && isset($variables['value']) && is_array($variables['value'])) {
    // The 'value', which is array needs to be removed from variables.
    // Otherwise details.html.twig will attempt to render it as a render
    // array, and will fail, because value is not renderable.
    unset($variables['value']);
  }
}

// vim: set ft=php:
