<?php declare(strict_types=1);

/*
 * This file is part of ptomulik/icon_bundle_api.
 *
 * Copyright (c) Paweł Tomulik <ptomulik@meil.pw.edu.pl>
 *
 * View the LICENSE file for full copyright and license information.
 */

function icon_bundle_api_preprocess_details(array &$variables, string $hook): void
{
    $element = $variables['element'];
    if ('icon_picker' === $element['#type'] && isset($variables['value']) && is_array($variables['value'])) {
        unset($variables['value']);
    }
}

// vim: set ft=php:
